# Generated by Django 2.2.5 on 2019-09-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190925_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuongtrinhdaotao',
            name='tuchon',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
