# Generated by Django 2.2.5 on 2019-09-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_chuongtrinhdaotao_tuchon'),
    ]

    operations = [
        migrations.AddField(
            model_name='diem',
            name='ctdt',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='student.ChuongTrinhDaoTao'),
        ),
        migrations.AlterField(
            model_name='diem',
            name='hocphan',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='student.HocPhan'),
        ),
    ]
